# Generated by Django 5.2.11 on 2026-07-31 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_api', '0004_nextjsdeployment_signing_key_hash_and_more'),
        # Must run AFTER webhooks owns the models, or the FK from
        # WebhookDelivery -> Webhook has no target in migration state.
        ('webhooks', '0001_initial'),
    ]

    # State-only counterpart to webhooks/0001_initial. The rows stay exactly where
    # they are; this only removes the models from this app's migration state.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='webhookdelivery',
                    name='webhook',
                ),
                migrations.AlterUniqueTogether(
                    name='webhookdelivery',
                    unique_together=None,
                ),
                migrations.DeleteModel(
                    name='Webhook',
                ),
                migrations.DeleteModel(
                    name='WebhookDelivery',
                ),
            ],
            database_operations=[],
        ),
    ]
