# Generated by Django 5.2.11 on 2026-06-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_user_has_seen_product_tour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="payment_subscription_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
    ]
