# Generated by Django 5.2.11 on 2026-06-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_subscription_payment_subscription_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoicerecord",
            name="currency",
            field=models.CharField(default="gbp", max_length=3),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="currency",
            field=models.CharField(default="gbp", max_length=3),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.CharField(
                choices=[
                    ("starter", "Self-Serve Brand"),
                    ("pro", "Managed Growth Brand"),
                    ("business", "Max"),
                ],
                default="starter",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EnterpriseLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=255)),
                ("website", models.CharField(blank=True, default="", max_length=255)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "prompts_required",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("brands_count", models.PositiveIntegerField(blank=True, null=True)),
                ("current_investment", models.TextField(blank=True, default="")),
                (
                    "support_level",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "preferred_currency",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                ("team_size", models.CharField(blank=True, default="", max_length=64)),
                ("ai_engines", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="accounts_en_status_75c727_idx",
                    )
                ],
            },
        ),
    ]
