# Generated by Django 5.2.11 on 2026-07-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_accountprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountprofile",
            name="agency_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
