# Generated by Django 5.2.11 on 2026-07-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_accountprofile_agency_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountprofile",
            name="role",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
