# Generated by Django 5.2.11 on 2026-07-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_accountprofile_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgencyMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agency_email", models.EmailField(db_index=True, max_length=254)),
                ("member_email", models.EmailField(db_index=True, max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("member", "Member")],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("invited", "Invited"), ("active", "Active")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "invited_by",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "accounts_agency_membership",
                "unique_together": {("agency_email", "member_email")},
            },
        ),
    ]
