# Generated by Django 5.2.11 on 2026-08-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_agencymembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('starter', 'Self-Serve Brand'), ('agency', 'Agency Starter'), ('pro', 'Managed Growth Brand'), ('business', 'Max')], default='starter', max_length=20),
        ),
    ]
