# Generated by Django 5.2.6 on 2026-06-08 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0008_alter_integration_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="provider",
            field=models.CharField(
                choices=[
                    ("google_analytics", "Google Analytics"),
                    ("google_search_console", "Google Search Console"),
                    ("shopify", "Shopify"),
                    ("wordpress", "WordPress"),
                    ("woocommerce", "WooCommerce"),
                    ("webflow", "Webflow"),
                    ("nextjs", "Next.js"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="GSCDataSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                ("clicks", models.IntegerField(default=0)),
                ("impressions", models.IntegerField(default=0)),
                ("ctr", models.FloatField(default=0)),
                ("position", models.FloatField(default=0)),
                ("daily_trend", models.JSONField(blank=True, default=list)),
                ("top_queries", models.JSONField(blank=True, default=list)),
                ("top_pages", models.JSONField(blank=True, default=list)),
                ("countries", models.JSONField(blank=True, default=list)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("syncing", "Syncing"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gsc_snapshots",
                        to="integrations.integration",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["integration", "-created_at"],
                        name="integration_integra_e24cd5_idx",
                    )
                ],
            },
        ),
    ]
