# Generated by Django 5.2.11 on 2026-06-25 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0009_alter_integration_provider_gscdatasnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="GSCIndexStatusSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checked_count", models.IntegerField(default=0)),
                ("indexed_count", models.IntegerField(default=0)),
                ("not_indexed_count", models.IntegerField(default=0)),
                ("sitemap_total", models.IntegerField(default=0)),
                ("submitted", models.IntegerField(default=0)),
                ("pages", models.JSONField(blank=True, default=list)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("syncing", "Syncing"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gsc_index_snapshots",
                        to="integrations.integration",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["integration", "-created_at"],
                        name="integration_integra_27d38b_idx",
                    )
                ],
            },
        ),
    ]
