# Generated by Django 5.2.11 on 2026-07-31 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_gscindexstatussnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='provider',
            field=models.CharField(choices=[('google_analytics', 'Google Analytics'), ('google_search_console', 'Google Search Console'), ('shopify', 'Shopify'), ('wordpress', 'WordPress'), ('woocommerce', 'WooCommerce'), ('webflow', 'Webflow'), ('nextjs', 'Next.js'), ('framer', 'Framer'), ('github', 'GitHub')], max_length=30),
        ),
    ]
