# Generated by Django 5.2.11 on 2026-05-08 07:37

from django.db import migrations, models


def _existing_columns(schema_editor, table):
    return {
        col.name
        for col in schema_editor.connection.introspection.get_table_description(
            schema_editor.connection.cursor(), table
        )
    }


def add_storefront_password(apps, schema_editor):
    table = "analyzer_analysisrun"
    if "storefront_password" in _existing_columns(schema_editor, table):
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f'ALTER TABLE "{table}" ADD COLUMN "storefront_password" '
            "VARCHAR(255) NOT NULL DEFAULT '';"
        )


def drop_storefront_password(apps, schema_editor):
    table = "analyzer_analysisrun"
    if "storefront_password" not in _existing_columns(schema_editor, table):
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f'ALTER TABLE "{table}" DROP COLUMN "storefront_password";')


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0035_merge_20260424_0957'),
    ]

    # Wrap the column add in SeparateDatabaseAndState so Django updates its
    # model state regardless, but the DB op is idempotent via a column-exists
    # check — staging already has this column from a previous deploy and
    # would otherwise fail with `DuplicateColumn`. Uses RunPython (not
    # RunSQL with `IF NOT EXISTS`) so it also works on SQLite (dev), which
    # doesn't support that clause.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_storefront_password, reverse_code=drop_storefront_password),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='analysisrun',
                    name='storefront_password',
                    field=models.CharField(blank=True, default='', max_length=255),
                ),
            ],
        ),
    ]
