# Generated by Django 5.2.11 on 2026-06-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0046_drop_prompttrack_mentioned_competitors"),
        ("organizations", "0004_organization_normalized_url_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="analysisrun",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="analyzer_an_organiz_5fc3e0_idx",
            ),
        ),
    ]
