# Generated by Django 5.2.11 on 2026-06-24 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0047_recommendation_daily_priority_rank_and_more'),
        ('organizations', '0004_organization_normalized_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteBlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('research', 'Research'), ('listicals', 'Listicals'), ('market_trends', 'Market Trends')], db_index=True, max_length=20)),
                ('slug', models.CharField(db_index=True, max_length=160)),
                ('title', models.CharField(max_length=300)),
                ('meta_description', models.CharField(blank=True, default='', max_length=320)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('content_html', models.TextField(blank=True, default='')),
                ('content_markdown', models.TextField(blank=True, default='')),
                ('brand_url', models.URLField(blank=True, default='', max_length=2048)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satellite_blog_posts', to='analyzer.analysisrun')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='satellite_blog_posts', to='organizations.organization')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['site', 'status'], name='analyzer_sa_site_507624_idx'), models.Index(fields=['organization', 'status'], name='analyzer_sa_organiz_035df8_idx')],
                'constraints': [models.UniqueConstraint(fields=('site', 'slug'), name='uniq_satellite_site_slug')],
            },
        ),
    ]
