# Generated by Django 5.2.11 on 2026-06-26 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0047_analysisrun_analyzer_an_organiz_5fc3e0_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="source",
            field=models.CharField(
                choices=[("analyzer", "Analyzer"), ("ai_insight", "AI Insight")],
                db_index=True,
                default="analyzer",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="OverviewInsightReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("has_ga", models.BooleanField(default=False)),
                ("has_gsc", models.BooleanField(default=False)),
                ("generated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overview_insights",
                        to="analyzer.analysisrun",
                    ),
                ),
            ],
        ),
    ]
