# Generated by Django 5.2.11 on 2026-07-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0048_recommendation_source_overviewinsightreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraction",
            name="assignee_email",
            field=models.EmailField(
                blank=True, db_index=True, default="", max_length=254
            ),
        ),
    ]
