# Generated by Django 5.2.11 on 2026-07-03 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0050_recommendation_source'),
        ('organizations', '0004_organization_normalized_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacklinkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('run_slug', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('next_run_at', models.DateTimeField()),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_batch_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backlink_schedules', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['next_run_at', 'is_active'], name='analyzer_ba_next_ru_0c7c5a_idx')],
                'unique_together': {('organization', 'email')},
            },
        ),
    ]
