# Generated by Django 5.2.11 on 2026-07-09 04:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0049_useraction_assignee_email"),
        ("analyzer", "0051_backlinkschedule"),
    ]

    operations = []
