# Generated by Django 5.2.6 on 2026-07-15 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0052_merge_20260709_1027"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptEvalLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt_name", models.CharField(db_index=True, max_length=64)),
                ("prompt_version", models.CharField(max_length=16)),
                ("case_id", models.CharField(blank=True, default="", max_length=128)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("recorded", "Recorded known-good"),
                            ("live", "Live generation"),
                        ],
                        default="recorded",
                        max_length=12,
                    ),
                ),
                ("faithfulness", models.FloatField(default=0.0)),
                ("relevance", models.FloatField(default=0.0)),
                ("format_score", models.FloatField(default=0.0)),
                ("passed", models.BooleanField(db_index=True, default=False)),
                ("rationale", models.TextField(blank=True, default="")),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                ("retrieved_chunks", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prompt_eval_logs",
                        to="analyzer.analysisrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["prompt_name", "prompt_version"],
                        name="analyzer_pr_prompt__c682cb_idx",
                    ),
                    models.Index(
                        fields=["prompt_name", "passed"],
                        name="analyzer_pr_prompt__2d78dd_idx",
                    ),
                ],
            },
        ),
    ]
