# Generated by Django 5.2.6 on 2026-07-15 05:09

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models

_INDEX = "llm_cache_embedding_hnsw"
_TABLE = "analyzer_llmresponsecache"
_CREATE = (
    f"CREATE INDEX IF NOT EXISTS {_INDEX} ON {_TABLE} "
    "USING hnsw (prompt_embedding vector_cosine_ops) "
    "WHERE prompt_embedding IS NOT NULL"
)
_DROP = f"DROP INDEX IF EXISTS {_INDEX}"


def _create_index(apps, schema_editor):
    # Postgres-only; a clean no-op on SQLite (dev fallback / test DB).
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(_CREATE)


def _drop_index(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(_DROP)


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0053_promptevallog"),
        ("organizations", "0009_corpus_hnsw_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMResponseCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purpose", models.CharField(db_index=True, max_length=128)),
                ("model_key", models.CharField(max_length=64)),
                ("prompt_hash", models.CharField(db_index=True, max_length=64)),
                ("prompt_text", models.TextField(blank=True, default="")),
                (
                    "prompt_embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=768, null=True
                    ),
                ),
                ("response_text", models.TextField()),
                ("hit_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_response_cache",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["purpose", "model_key", "organization"],
                        name="analyzer_ll_purpose_1bcdd9_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="analyzer_ll_expires_110df8_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("purpose", "model_key", "organization", "prompt_hash"),
                        name="uniq_llm_cache_scope_hash",
                    )
                ],
            },
        ),
        migrations.RunPython(_create_index, _drop_index),
    ]
