# Generated by Django 5.2.11 on 2026-07-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0054_llmresponsecache'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='useraction',
            index=models.Index(fields=['assignee_email', 'status'], name='analyzer_us_assigne_8eebd4_idx'),
        ),
    ]
