# Generated by Django 5.2.11 on 2026-07-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0055_useraction_assignee_status_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptresult',
            name='engine',
            field=models.CharField(choices=[('chatgpt', 'ChatGPT'), ('claude', 'Claude'), ('gemini', 'Gemini'), ('perplexity', 'Perplexity'), ('google', 'Google'), ('bing', 'Bing'), ('deepseek', 'DeepSeek'), ('grok', 'Grok'), ('llama', 'Meta Llama')], max_length=20),
        ),
    ]
