# Generated by Django 5.2.11 on 2026-07-17 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0056_alter_promptresult_engine'),
        ('organizations', '0009_corpus_hnsw_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot', models.CharField(max_length=40)),
                ('path', models.CharField(blank=True, default='/', max_length=512)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('hit_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawler_hits', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'hit_at'], name='analyzer_cr_organiz_08c260_idx')],
            },
        ),
    ]
