# Generated by Django 5.2.11 on 2026-07-18 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0057_crawlerhit'),
        ('organizations', '0009_corpus_hnsw_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=40)),
                ('handle', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('status', models.CharField(blank=True, default='', max_length=20)),
                ('price', models.CharField(blank=True, default='', max_length=40)),
                ('description_chars', models.IntegerField(default=0)),
                ('images_total', models.IntegerField(default=0)),
                ('images_missing_alt', models.IntegerField(default=0)),
                ('readiness', models.IntegerField(default=0)),
                ('issues', models.JSONField(default=list)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopify_products', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'readiness'], name='analyzer_sh_organiz_fef634_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'product_id'), name='uniq_org_shopify_product')],
            },
        ),
    ]
