# Generated by Django 5.2.11 on 2026-07-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0059_analysisrun_email_created_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='affected_pages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='generated_content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='impact_points',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='source',
            field=models.CharField(choices=[('analyzer', 'Analyzer'), ('ai_insight', 'AI Insight'), ('geo_signal', 'GEO Signal')], db_index=True, default='analyzer', max_length=20),
        ),
    ]
