# Generated by Django 5.2.11 on 2026-07-24 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0061_useraction_verification_message'),
        ('organizations', '0009_corpus_hnsw_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSatisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=2048)),
                ('finding_code', models.CharField(db_index=True, max_length=80)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('source', models.CharField(choices=[('heuristic', 'Heuristic'), ('llm', 'LLM'), ('autofix', 'Auto-fix'), ('recheck', 'Daily recheck'), ('user', 'User')], default='heuristic', max_length=20)),
                ('confidence', models.FloatField(default=1.0)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_satisfactions', to='organizations.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'page_url', 'finding_code'), name='uniq_task_satisfaction')],
            },
        ),
    ]
