# Generated by Django 5.2.11 on 2026-07-25 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0062_task_satisfaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='impact_points',
        ),
    ]
