# Generated by Django 5.2.11 on 2026-07-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0063_remove_recommendation_impact_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='llm_cost_usd',
            field=models.FloatField(db_index=True, default=0.0),
        ),
    ]
