# Generated by Django 5.2.11 on 2026-07-29 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0064_analysisrun_llm_cost_usd'),
        ('organizations', '0009_corpus_hnsw_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitationOutreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('pitched', 'Pitched'), ('dismissed', 'Not pursuing')], default='identified', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citation_outreach', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'status'], name='analyzer_ci_organiz_bcadce_idx')],
                'unique_together': {('organization', 'domain')},
            },
        ),
    ]
