# Generated by Django 5.2.11 on 2026-07-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0065_citation_outreach'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='phase',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
    ]
