# Generated by Django 5.2.11 on 2026-08-01 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0066_analysisrun_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityResolutionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(default=dict)),
                ('probed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entity_resolution', to='analyzer.analysisrun')),
            ],
        ),
    ]
