# Generated by Django 5.2.11 on 2026-08-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0067_entityresolutionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='outreach_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='run_type',
            field=models.CharField(choices=[('single_page', 'Single Page'), ('full_site', 'Full Site'), ('outreach', 'Outreach')], default='single_page', max_length=20),
        ),
    ]
