"""Deterministic crawl-directive files (Epic 8).

robots.txt is fully determined by the site URL plus a fixed list of AI crawlers, so it is
built from a template here rather than generated by an LLM. The previous LLM-generated
version cost a call per fix and could hallucinate a ``Disallow`` -- a mistake that can
deindex a site. One builder, one source of truth, used by every fix path.
"""

from __future__ import annotations

# Crawlers we explicitly welcome. Keeping the list here (not in a prompt) means adding a
# bot is a one-line change with no model involved.
AI_CRAWLERS = (
    "GPTBot",
    "ClaudeBot",
    "Google-Extended",
    "PerplexityBot",
    "ChatGPT-User",
    "CCBot",
)


def build_robots_txt(site_url: str) -> str:
    """A permissive robots.txt that allows all crawlers, names the AI bots explicitly,
    and points at the sitemap."""
    base = (site_url or "").rstrip("/")
    lines = ["User-agent: *", "Allow: /", ""]
    for bot in AI_CRAWLERS:
        lines += [f"User-agent: {bot}", "Allow: /", ""]
    if base:
        lines.append(f"Sitemap: {base}/sitemap.xml")
    return "\n".join(lines).strip() + "\n"
