# Generated by Django 5.2.11 on 2026-06-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_agent", "0002_githubfixjob_reasoning"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubfixjob",
            name="content_edits",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
