# Generated by Django 5.2.11 on 2026-07-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_agent', '0003_githubfixjob_content_edits'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubinstallation',
            name='repo_detection',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='githubinstallation',
            name='repo_locked',
            field=models.BooleanField(default=False),
        ),
    ]
