# Generated by Django 5.2.11 on 2026-07-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_agent', '0004_githubinstallation_repo_detection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubfixjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('open', 'Open'), ('merged', 'Merged'), ('closed', 'Closed'), ('declined', 'Declined'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
