"""IndexNow: push URLs into Bing's index, which is what ChatGPT search reads.

Everything in this product optimises what an engine finds *once it looks*. This
is about getting looked at. ChatGPT's live search leans on Bing, and Bing will
not answer from a page it has not indexed - which is why a site can be perfectly
configured, allowed by robots.txt, and still invisible to ChatGPT.

IndexNow is the cheap half of the fix: no OAuth, no account linking, no API
approval. The site hosts a key file, and a single POST tells Bing, Yandex, Seznam
and Naver that a set of URLs changed. Submissions are shared between
participating engines, so one call covers all of them.

Two things it deliberately does not do:

* **It does not claim indexing.** A successful submission means the engine
  accepted the request, not that the page was indexed or ranked. Reporting
  "submitted" as "indexed" would be the same class of lie as a self-reported
  outreach tracker.
* **It does not submit without verifying the key file first.** An unverified
  submission returns 403 and burns the quota, and worse, it looks successful in a
  UI that only counts requests sent.
"""

from __future__ import annotations

import logging
from dataclasses import asdict, dataclass, field

import requests
from django.core import signing

logger = logging.getLogger("apps")

# The shared IndexNow endpoint. Participating engines forward between themselves,
# so one submission reaches all of them.
ENDPOINT = "https://api.indexnow.org/indexnow"

# IndexNow caps a batch at 10,000; stay well under and keep payloads small.
MAX_URLS = 500
TIMEOUT_SEC = 15

# Response codes IndexNow defines, mapped to something a user can act on.
_STATUS_MEANING = {
    200: "Accepted. The URLs were passed to participating engines.",
    202: "Accepted, pending key validation. The key file must stay reachable.",
    400: "Bad request - the URL list was rejected.",
    403: "Key not valid. The key file is missing or does not match.",
    422: "URLs do not belong to the host, or the key does not match the host.",
    429: "Too many requests. Wait before submitting again.",
}


@dataclass
class SubmissionResult:
    submitted: int
    status_code: int | None
    ok: bool
    message: str
    urls: list[str] = field(default_factory=list)

    def as_dict(self) -> dict:
        return asdict(self)


def _signer() -> signing.Signer:
    return signing.Signer(salt="indexnow-key")


def key_for_org(org_id: int) -> str:
    """Deterministic, org-scoped IndexNow key.

    Derived from the signing key rather than stored, matching how the crawler
    ingest token works: no migration, no secret at rest, and it cannot be
    regenerated by accident. IndexNow requires 8-128 hex-ish characters.
    """
    signed = _signer().sign(str(org_id))
    import hashlib

    return hashlib.sha256(signed.encode()).hexdigest()[:32]


def key_file_url(site_url: str, key: str) -> str:
    """Where the key file must live: ``https://host/<key>.txt``."""
    from urllib.parse import urlparse

    parsed = urlparse(site_url or "")
    host = parsed.netloc
    scheme = parsed.scheme or "https"
    return f"{scheme}://{host}/{key}.txt" if host else ""


def verify_key_file(site_url: str, key: str) -> tuple[bool, str]:
    """Whether the key file is hosted and contains the key.

    Checked before every submission because an unverified key produces a 403
    that a naive UI would still render as "submitted".
    """
    url = key_file_url(site_url, key)
    if not url:
        return False, "No site URL to check."
    try:
        resp = requests.get(url, timeout=TIMEOUT_SEC, allow_redirects=True)
    except requests.RequestException as exc:
        return False, f"Could not fetch {url}: {exc}"
    if resp.status_code != 200:
        return False, f"{url} returned HTTP {resp.status_code}. Host the key file there."
    if resp.text.strip() != key:
        return False, f"{url} exists but does not contain the key."
    return True, "Key file verified."


def submit(site_url: str, urls: list[str], *, key: str) -> SubmissionResult:
    """Submit changed URLs to IndexNow. Never raises.

    Verifies the key file first: a submission against a missing key wastes the
    request and reports success to anyone counting HTTP calls rather than
    outcomes.
    """
    from urllib.parse import urlparse

    host = urlparse(site_url or "").netloc
    clean = [u for u in dict.fromkeys(urls or []) if u.startswith(("http://", "https://"))]
    # IndexNow rejects a batch containing a URL from another host, so filter
    # rather than let one stray URL fail the whole submission.
    clean = [u for u in clean if urlparse(u).netloc == host][:MAX_URLS]

    if not host or not clean:
        return SubmissionResult(0, None, False, "No submittable URLs for this host.")

    ok, message = verify_key_file(site_url, key)
    if not ok:
        return SubmissionResult(0, None, False, message)

    payload = {"host": host, "key": key, "keyLocation": key_file_url(site_url, key), "urlList": clean}
    try:
        resp = requests.post(ENDPOINT, json=payload, timeout=TIMEOUT_SEC)
    except requests.RequestException as exc:
        logger.warning("indexnow: submission failed for %s: %s", host, exc)
        return SubmissionResult(0, None, False, f"Submission failed: {exc}")

    accepted = resp.status_code in (200, 202)
    return SubmissionResult(
        submitted=len(clean) if accepted else 0,
        status_code=resp.status_code,
        ok=accepted,
        message=_STATUS_MEANING.get(resp.status_code, f"Unexpected response: HTTP {resp.status_code}"),
        urls=clean[:20],
    )


def setup_for_run(run) -> dict:
    """Key, key-file location and current verification state for a run's site."""
    org = getattr(run, "organization", None)
    if org is None:
        return {"configured": False, "detail": "Run has no organization."}

    key = key_for_org(org.id)
    verified, message = verify_key_file(run.url, key)
    return {
        "configured": True,
        "key": key,
        "key_file_url": key_file_url(run.url, key),
        "key_file_contents": key,
        "verified": verified,
        "message": message,
        "why": (
            "ChatGPT's live search reads Bing's index. IndexNow pushes changed pages "
            "to Bing, Yandex, Seznam and Naver in one call, so new content is "
            "discoverable in hours rather than whenever a crawler next visits."
        ),
    }


def submit_run_pages(run, urls: list[str] | None = None) -> dict:
    """Submit a run's known pages. Falls back to every scored page URL."""
    org = getattr(run, "organization", None)
    if org is None:
        return SubmissionResult(0, None, False, "Run has no organization.").as_dict()

    targets = urls or list(run.page_scores.values_list("url", flat=True)) or [run.url]
    return submit(run.url, targets, key=key_for_org(org.id)).as_dict()
