# Generated by Django 5.2.11 on 2026-07-13 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0052_merge_20260709_1027"),
        ("organizations", "0006_organization_platform"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("identity", models.JSONField(blank=True, default=dict)),
                ("positioning", models.JSONField(blank=True, default=dict)),
                ("audience", models.JSONField(blank=True, default=dict)),
                ("voice", models.JSONField(blank=True, default=dict)),
                ("canonical_facts", models.JSONField(blank=True, default=dict)),
                ("competitors", models.JSONField(blank=True, default=list)),
                ("sources", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_profile",
                        to="organizations.organization",
                    ),
                ),
                (
                    "source_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="brand_profiles",
                        to="analyzer.analysisrun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status"], name="organizatio_status_0ea59a_idx"
                    )
                ],
            },
        ),
    ]
