# Generated by Django 5.2.6 on 2026-07-14 05:18

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    """Adds the org knowledge base (Epic 3).

    ``VectorExtension`` runs ``CREATE EXTENSION IF NOT EXISTS vector`` on Postgres
    (a no-op on other backends, so SQLite tests are unaffected). Neon supports
    pgvector natively. If the app's DB role lacks CREATE-EXTENSION rights, an
    operator must run ``CREATE EXTENSION vector;`` once as a superuser before this
    migration is applied.
    """

    dependencies = [
        ("analyzer", "0052_merge_20260709_1027"),
        ("organizations", "0007_brandprofile"),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name="BrandCorpusChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_url", models.URLField(db_index=True, max_length=2048)),
                ("heading_path", models.JSONField(blank=True, default=list)),
                ("text", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=768, null=True
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corpus_chunks",
                        to="organizations.organization",
                    ),
                ),
                (
                    "source_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="corpus_chunks",
                        to="analyzer.analysisrun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "is_current"],
                        name="organizatio_organiz_452711_idx",
                    ),
                    models.Index(
                        fields=["organization", "source_url", "is_current"],
                        name="organizatio_organiz_1eb45b_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "source_url", "content_hash"),
                        name="uniq_corpus_chunk",
                    )
                ],
            },
        ),
    ]
